FROM maven:3.9.11-eclipse-temurin-24-alpine AS build-stage
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn package -DskipTests

FROM eclipse-temurin:24.0.2_12-jre-alpine AS final-stage
WORKDIR /app

COPY --from=build-stage /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]